### PR TITLE
Audit findings

### PR DESCRIPTION
**Pull request by mh-targens**

### CODE REVIEW

**Review by rya-sge — COMMENTED** [review]
Hi thank you very much for your modifications

For the solidity version (CVF 21), 
-Why use the version 0.8.12 ?
-Why not use the same version and notation than for DVP.sol ?

**Comment by mh-targens** [comment]
> Hi thank you very much for your modifications
> 
> For the solidity version (CVF 21), -Why use the version 0.8.12 ? -Why not use the same version and notation than for DVP.sol ?

All contracts now use 0.8.17

**Comment by sbisig** [comment]
@veorq Please accept PL now. We are fine with the generic ERC20 error messages separately handling insufficient allowance and balance, instead of explicit testing within DvP and therefore additional gas costs. (as mentioned in the security audit)

**Review by rya-sge — APPROVED** [review]
All is good +1:

**Pull request merged**
